server:
 port: 10077
 servlet:
  context-path: /cimServer
spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
logging:
  level:
    org.riozenc.cim: debug
  path: log