server:
 port: 9922
spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
logging:
  level:
    org.gateway: debug
    org.springframework.cloud.gateway: debug
  path: log